spring.application.name=DigitalBankingApplication
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/digital_banking_db

spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=DigitalBankingSecretKeyForJwtAuthenticationSystem

jwt.expiration=86400000